language: node_js
node_js:
- '6'
sudo: false
before_script: npm run build
deploy:
  provider: npm
  email: erik.gustav.dalen@gmail.com
  api_key:
    secure: GWinLrQxnnIYgwUcJAupGPKfGh/oYH86ugeFU87EMfX+0qPDcBULnhDJ/r8AYGPfsdEOIa0mhf2wN3lR4lY+z+Gu0k9KRJ6SnJ087mI20bHEFUI9OMZlqpz56qWQbAB2bEOJkRtBf7LWWqonW9VvPluRs/E+u+GwIfYenXLmMq0=
  on:
    tags: true
    repo: dalen/node-puppetdbquery
